# Generated by Django 4.0.3 on 2022-04-06 07:23

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('jno', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=30)),
                ('brand', models.CharField(choices=[(1, 'royal enfield'), (2, 'KTM'), (3, 'yamaha')], max_length=1)),
                ('model', models.CharField(max_length=10)),
                ('complaint', models.TextField(blank=True)),
                ('warranty', models.CharField(choices=[(1, 'Yes'), (2, 'Nil')], max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(default=1, max_length=128, region=None, unique=True)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
    ]
