# Generated by Django 4.0.3 on 2022-04-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobslip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='brand',
            field=models.CharField(choices=[(1, 'Royal enfield'), (2, 'KTM'), (3, 'Yamaha'), (4, 'TVS'), (5, 'Bajaj'), (6, 'Honda')], max_length=1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='warranty',
            field=models.CharField(choices=[(1, 'Yes'), (2, 'Nil')], max_length=1),
        ),
    ]
