# Generated by Django 4.0.3 on 2022-04-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobslip', '0002_alter_customer_brand_alter_customer_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
