# Generated by Django 4.0.3 on 2022-04-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobslip', '0003_alter_customer_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=models.IntegerField(blank=True),
        ),
    ]
