# Generated by Django 4.0.3 on 2022-04-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobslip', '0005_alter_customer_warranty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='brand',
            field=models.CharField(choices=[(1, 'Royal enfield'), (2, 'KTM'), (3, 'Yamaha'), (4, 'TVS'), (5, 'Bajaj'), (6, 'Honda')], max_length=3),
        ),
    ]
