# Generated by Django 4.0.3 on 2022-04-06 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobslip', '0007_alter_customer_brand_alter_customer_warranty'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
    ]
