# Generated by Django 4.0.3 on 2022-04-06 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobslip', '0008_alter_customer_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='Customer',
        ),
    ]
